import type { Catalog, ClassDef, Source } from './types.js';

export const STAGE_NAMES = ['absent', 'tried', 'works', 'reliable', 'controlled', 'exemplary'] as const;
export const REPO_URL = 'https://github.com/master5d/awesome-checkup';

function sourceLine(s: Source, cat: Catalog): string {
  if ('scar' in s) return `scar: [${cat.scars[s.scar] ?? s.scar}](../scars/${s.scar}.md)`;
  const st = cat.standards.find((x) => x.id === s.standard);
  return st ? `standard: [${st.name}](${st.url})` : `standard: ${s.standard}`;
}

export function renderClassMd(cls: ClassDef, cat: Catalog): string {
  const out: string[] = [
    `<!-- generated from checklists/${cls.id}.yaml by scripts/render.ts — edit the yaml, not this file -->`,
    `# ${cls.title}`,
    '',
    cls.summary.trim(),
    '',
    'Stages: 1 tried · 2 works · 3 reliable · 4 controlled · 5 exemplary. Run `npx awesome-checkup` to score your setup.',
    '',
  ];
  for (let st = 1; st <= 5; st++) {
    const items = cls.items.filter((i) => i.stage === st);
    if (items.length === 0) continue;
    out.push(`## Stage ${st} — ${STAGE_NAMES[st]}`, '');
    for (const it of items) {
      out.push(`### ${it.id}`, '', `- [ ] ${it.check.trim()}`, '', `**Why:** ${it.why.trim()}`, '');
      for (const s of it.sources) out.push(`- ${sourceLine(s, cat)}`);
      out.push(it.probe ? `- auto-check: \`${it.probe}\`` : '- auto-check: none — asked interactively', '');
    }
  }
  return out.join('\n');
}

export function renderReadme(cat: Catalog): string {
  const rows = cat.classes.map((c) => {
    const auto = c.items.filter((i) => i.probe).length;
    const stages = [...new Set(c.items.map((i) => i.stage))].sort().join(', ');
    return `| [${c.title}](checklists/${c.id}.md) | ${c.items.length} | ${auto} | ${stages} |`;
  });
  return [
    '<!-- generated by scripts/render.ts — edit checklists/*.yaml, not this file -->',
    '# awesome-checkup',
    '',
    '> Checklists for a one-person agentic lab — every item is backed by a scar (something that went wrong) or a published standard.',
    '',
    '```bash',
    'npx awesome-checkup            # auto-checks your repo, asks about the rest, prints a scorecard',
    'npx awesome-checkup --no-ask   # CI mode: auto-checks only',
    '```',
    '',
    'Zero network calls. Nothing leaves your machine.',
    '',
    '## Stages',
    '',
    '| Stage | Name | Meaning |',
    '| --- | --- | --- |',
    '| 0 | absent | nothing in place |',
    '| 1 | tried | first version exists |',
    '| 2 | works | it does its job day to day |',
    '| 3 | reliable | failures are caught, not discovered |',
    '| 4 | controlled | measured, with owners and limits |',
    '| 5 | exemplary | others could copy it |',
    '',
    '## Classes',
    '',
    '| Class | Items | Auto-checked | Stages covered |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
    '## How scoring works',
    '',
    '- A class is at stage N only when every item at stages 1..N is verified.',
    '- `?` (not verified) is never counted as passed — and never as zero. The card shows how far you could get if the unknowns pass.',
    '- Classes are shown side by side. There is no single number: one would hide the weakest class.',
    '',
    '## Contributing',
    '',
    'Every new item needs a source: a scar (`scars/<id>.md`) or a standard (`standards.yaml`). See [CONTRIBUTING.md](CONTRIBUTING.md).',
    '',
    '## License',
    '',
    'Code: MIT. Checklists, scars and standards list: CC BY 4.0.',
    '',
  ].join('\n');
}

export function renderDataModule(cat: Catalog): string {
  return [
    '// generated by scripts/render.ts — do not edit',
    "import type { Catalog } from './types.js';",
    '',
    `export const CATALOG: Catalog = ${JSON.stringify(cat, null, 2)};`,
    '',
  ].join('\n');
}
